version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - go mod download
      - npm install

  build:
    desc: Build the project
    cmds:
      - npx @tailwindcss/cli -i assets/css/styles.css -o assets/css/globals.css --minify
      - npx esbuild assets/js/app.js --minify --outfile=assets/js/app.min.js
      - templ generate
      - go build -ldflags "-s -w" -o main cmd/server/main.go
    env:
      CGO_ENABLED: 0

  templ:
    desc: Start templ in watch mode
    cmds:
      - templ generate --watch --proxy="http://localhost:5000" --proxyport=3000

  tailwind:
    desc: Start tailwind in watch mode
    cmds:
      - npx @tailwindcss/cli -i assets/css/styles.css -o assets/css/globals.css --watch

  js:
    desc: Start esbuild in watch mode
    cmds:
      - npx esbuild assets/js/app.js --outfile=assets/js/app.min.js --watch

  server:
    desc: Start live server
    cmds:
      - air
    env:
      PORT: 5000

  dev:
    desc: Start development server
    run: always
    deps:
      - server
      - tailwind
      - js
      - templ
