version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - npm install
      - go mod tidy

  build:
    desc: Build the project
    cmds:
      - npx tailwindcss build -i assets/css/styles.css -o assets/css/globals.css --minify
      - templ generate
      - go build -ldflags "-s -w" pkg/server/main.go
    env:
      CGO_ENABLED: 0

  templ:
    desc: Start templ in watch mode
    cmds:
      - templ generate --watch --proxy="http://localhost:5000" --proxyport=3000

  tailwind:
    desc: Start tailwind in watch mode
    cmds:
      - npx tailwindcss build -i assets/css/styles.css -o assets/css/globals.css --watch

  server:
    desc: Start live server
    cmds:
      - air

  dev:
    desc: Start development server
    run: always
    deps:
      - server
      - tailwind
      - templ